# Generated by Django 3.1 on 2020-09-13 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20200911_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=datetime.datetime(2020, 9, 13, 7, 34, 16, 401208, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
