# Generated by Django 3.1 on 2020-09-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20200913_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='product_image',
        ),
    ]
